message:
  prefix: "§a[§dRconQQShop§a]"
  GiftTitle: "§e礼包列表"
  GiftItemTile: "§d你好！§c这是您的礼包"
  ItemTitle: "§a你的物品"
  command:
    user:
      - "§6==========§b[§cUser§b]§6=========="
      - "§a/myjoin gift §c查看当前所有礼包"
      - "§a/myjoin item §c查看所有物品"
    help:
      - "§6==========§b[§cRconQQShop§b]§6=========="
      - "§a/rqs getItem §c获取手中物品英文id"
      - "§6==========§b[§cItem§b]§6=========="
      - "§a/rqs help §c查看帮助指令"
      - "§a/rqs addItem [id] [物品英文id] §c给予一名玩家待领取物品"
      - "§a/rqs listItem [id] §c列出一名玩家当前待领取物品"
      - "§a/rqs removeItem [id] [物品英文id] §c删除一名玩家待领取物品"
      - "§a/rqs clearItem [id] §c删除一名玩家所有待领取物品"
      - "§6==========§b[§cGift§b]§6=========="
      - "§a/rqs gift §c打开现有礼包"
      - "§a/rqs gift [礼包名称] §c打开指定礼包"
      - "§a/rqs giftAdd [id] [礼包代码] §c给指定玩家添加一个礼包"
      - "§a/rqs giftdelete [id] [礼包代码] §c删除一名玩家的特定礼包"
      - "§a/rqs giftlist [id] §c列出当前玩家的所有礼包"
      - "§a/rqs giftclear [id] §c删除当前玩家的所有礼包"
    JoinMessage:
      - "§b----------------------------"
      - "§c您当前有§d /item_list_size/ §c个物品等待你领取！"
      - "§c输入/myjoin item §e进行领取物品!"
      - "§b/gift_list_size/个礼包待你领取！"
      - "§c输入/myjoin gift §e进行领取礼包!"
      - "§b----------------------------"
    error: "§c指令错误详细请使用/rqs help"
    erroruser: "§c指令错误详细请使用/myjoin help"
    GiftOpenError: "§c您当前没有任何礼包！"
    ItemOpenError: "§c您当前没有任何物品！"
    Permission: "§c抱歉哦！您的权限不足！"
    ListItem: "§a没发现这个玩家有任何物品！"
    ListItemError: "用法错误！§e正确用法§7:§a/rqs listItem [id] §c列出一名玩家当前上线会给予的物品"
    AddItem: "§b添加成功！"
    AddItemError: "§c添加失败！§e正确用法§7:§a/rqs addItem [id] [物品英文id] §c给予一名玩家上线给予的物品"
    RemoveItemError: "§c删除失败！§e正确用法§7:§a/rqs removeItem [id] [物品英文id] §c删除一名玩家上线会给予的物品"
    ClearItemError: "§c清除失败！§e正确用法§7:§a/rqs clearItem [id] §c删除一名玩家所有上线给予的物品"
    AddItemWron: "§c这不是一个有效的物品！"
    RemoveItem: "§c成功删除一个！"
    ClearItem: "§c成功清理掉全部物品！"
    GiftItemGuiError: "§c错误！没有找到这个礼包！"
    senderError: "§c此指令输入者必须是一名玩家！"
    GiftAdd: "§b添加成功！"
    GiftNot: "§c找不到此礼包！"
    GiftAddError: "§c添加失败！§e正确用法§7:§a/rqs giftAdd [id] [礼包代码] §c给指定玩家添加一个礼包"
    Giftdelete: "§a删除成功！"
    GiftdeleteError: "§c删除失败§e正确用法§7:§a/rqs giftdelete [id] [礼包代码] §c删除一名玩家的特定礼包"
    GiftclearError: "§c列出失败！§e正确用法§7:§a/rqs giftclear [id] §c删除当前玩家的所有礼包"
    Giftclear: "§c清理成功！"
    Giftlist: "§c当前玩家没有任何礼包！"
    GiftlistError: "§c用法错误"
Item:
  GiftMate: WOOL

